### ISSUE TITLE
Heyy! So I am getting this error whenever I load minecraft, and beacause of it, the texture for my item "ruby" is not coming

### ISSUE THREAD

**Issue by TheModd** [TechnoVisionDev/Fabric-Modding-Tutorial-1.16.4#1]
[13:23:27] [Worker-Main-13/WARN] (Minecraft) Unable to load model: 'copyoftutorial:ruby#inventory' referenced from: copyoftutorial:ruby#inventory: java.io.FileNotFoundException: copyoftutorial:models/item/ruby.json

**Comment by TheKodeToad** [comment]
You need to create "assets/copyoftutorial/models/item/ruby.json". It should look something like this:
```json
{
  "parent": "minecraft:item/generated",
  "textures": {
    "layer0": "copyoftutorial:items/ruby"
  }
}
```
In some cases it might be "item/ruby" if the texture is in the "item" folder.

**Comment by TheModd** [comment]
Thanks! You're series has been really helpfull. I hope there are more
advanced episodes to come.
Oh I was wondering.. How do I compile my fabric project into one .jar file.
